objectionary/eo-phi-normalizer

- site/docs/book.toml
- site/docs/src/contributing.md
> 220 support mathjax on the site

- .github/workflows/ghc.yml
> fix(ci): use macos-12

- eo-phi-normalizer/CHANGELOG.md
- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
- site/docs/src/installation.md
> 543 release v2.1.0

- eo-phi-normalizer/src/Language/EO/Phi/Syntax.hs
- eo-phi-normalizer/test/eo/phi/from-eo/as-phi.yaml
- site/docs/src/eo-phi-normalizer/dataize.md
- site/docs/src/eo-phi-normalizer/rewrite.md
> 545 pretty printing doesnt put enough eols

- eo-phi-normalizer/CHANGELOG.md
- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
- site/docs/src/installation.md
> 564 release v220

- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
> 567 cant install latest version 220

- eo-phi-normalizer/CHANGELOG.md
- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
- site/docs/src/installation.md
> 570 prepare release of v221

- eo-phi-normalizer/src/Language/EO/Phi/Syntax.hs
- eo-phi-normalizer/test/eo/phi/from-eo/as-phi.yaml
> 574 pretty printing is a bit off

- eo-phi-normalizer/app/Main.hs
>  TeX output is a not complete

- eo-phi-normalizer/src/Language/EO/Phi/Syntax.hs
> Fix handling trailing comma during pretty printing

- eo-phi-normalizer/CHANGELOG.md
- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
- site/docs/src/installation.md
> 591 prepare release of v222

- site/docs/src/contributing.md
> fix(site): include file via mdsh, not mdBook

- .github/workflows/ghc.yml
- Closes #637
Changes:
- Configured CI to run on PRs to `develop`
> Run CI on PRs to `develop`

- site/docs/src/eo-phi-normalizer/dataize.md
- Addresses #631
Changes:
- Removed the description of the dataization process
> Remove the description of dataization

- eo-phi-normalizer/test/eo/phi/dataization.yaml
> 652 use dependencies for EO 0.50.0

- eo-phi-normalizer/CHANGELOG.md
- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
- site/docs/src/installation.md
> 656 prepare release of v310

- eo-phi-normalizer/src/Language/EO/Phi/Pretty.hs
- eo-phi-normalizer/test/eo/phi/from-eo/as-phi.yaml
> 604 alpha-binding syntax is not understood now

- eo-phi-normalizer/src/Language/EO/Phi/Syntax.hs
- eo-phi-normalizer/test/eo/phi/from-eo/as-phi.yaml
> 616 sugar for data primitives

- eo-phi-normalizer/CHANGELOG.md
- eo-phi-normalizer/eo-phi-normalizer.cabal
- eo-phi-normalizer/package.yaml
- site/docs/src/installation.md
> 663 prepare release of v320

- eo-phi-normalizer/app/Main.hs
- eo-phi-normalizer/src/Language/EO/Phi/Pretty.hs
- eo-phi-normalizer/src/Language/EO/Phi/Syntax.hs
- site/docs/src/eo-phi-normalizer/dataize.md
- site/docs/src/eo-phi-normalizer/rewrite.md
> Support `--no-sugar` in `rewrite` and `dataize`
